# https://github.com/awesome-containers/static-bash
ARG STATIC_BASH_VERSION=5.2.15
ARG STATIC_BASH_IMAGE=ghcr.io/awesome-containers/static-bash

# https://github.com/awesome-containers/static-tar
ARG STATIC_TAR_VERSION=1.34
ARG STATIC_TAR_IMAGE=ghcr.io/awesome-containers/static-tar

# https://github.com/awesome-containers/alpine-build-essential
ARG BUILD_ESSENTIAL_VERSION=3.17
ARG BUILD_ESSENTIAL_IMAGE=ghcr.io/awesome-containers/alpine-build-essential


FROM $STATIC_BASH_IMAGE:$STATIC_BASH_VERSION-slim AS static-bash
FROM $STATIC_TAR_IMAGE:$STATIC_TAR_VERSION AS static-tar
FROM $BUILD_ESSENTIAL_IMAGE:$BUILD_ESSENTIAL_VERSION AS build

WORKDIR /src/tar
COPY --from=static-tar /bin/tar ./

RUN set -xeu; \
    upx --no-progress --no-color tar; \
    upx -t --no-progress --no-color tar; \
    chmod -cR 755 tar; \
    chown -cR 0:0 tar; \
    ! ldd tar && :; \
    ./tar --version

# slim static tar image
FROM static-bash
COPY --from=build /src/tar/tar /bin/
